apiVersion: v1
kind: Service
metadata:
  name: svc-alzatest-front
spec:
  type: ClusterIP
  selector:
    alzatest: front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-alzatest-front
spec:
  selector:
    matchLabels:
      alzatest: front
  replicas: 1
  template:
    metadata:
      labels:
        alzatest: front
    spec:
      containers:
      - name: container-front
        image: aimarlauzirika/alzatest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.8"
            memory: "400Mi"
          requests:
            cpu: "0.3"
            memory: "100Mi"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "topology.kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - app